[package]
name = "tetris"
version = "0.0.1"
authors = ["Flaviu-Dorin Toader <flaviu.toader@gmail.com>"]
build = "build.rs"

[dependencies]
sdl2 = "0.30.0"
rand = "0.3"

[features]
default = ["sdl2/image", "sdl2/ttf"]
